### ISSUE TITLE
Issue with the Microsoft.IdentityModel.Abstractions 

### ISSUE THREAD

**Issue by dkotars** [agallego-css/ewsgui#33]
Connect-EWSService : The following exception occurred while retrieving member "Build": "Could not load file or
assembly 'Microsoft.IdentityModel.Abstractions, Version=6.18.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or
one of its dependencies. The system cannot find the file specified."

**Comment by arachnosoft** [comment]
I got the same issue. Here is how I solved it "manually":

- go to https://www.nuget.org/packages/Microsoft.IdentityModel.Abstractions/6.18.0
- click on **Download Package** on the right
- extract (unzip) the .nupkg downloaded file using a standard ZIP tool like 7-zip (rename the file with a .zip extension if necessary)
- browse the extracted folder and search for the _Microsoft.IdentityModel.Abstractions.dll_ and _Microsoft.IdentityModel.Abstractions.xml_ files located into the **lib\net472** subfolder
- copy those two files in your **C:\Program Files\WindowsPowerShell\Modules\ewsgui\2.0.20\bin** folder
- edit the **C:\Program Files\WindowsPowerShell\Modules\ewsgui\2.0.20\ewsgui.psd1** file with a text editor like Notepad++
- search the line with the **RequiredAssemblies** variable and add the path to the .dll file you copied before:
`# Assemblies that must be loaded prior to importing this module
	RequiredAssemblies = @('bin\Microsoft.Exchange.WebServices.dll', 'bin\Microsoft.IdentityModel.Abstractions.dll')`
- save the file
- and, **most importantly, close your PowerShell window and re-open it again as Administrator, then `Start-EWSGui` again**

If you don't do the last step (close and restart the PowerShell terminal window), the modifications you made to the module files will not be applied!

I hope that @agallego-css will be able to fix this bug!

**Comment by agallego-css** [comment]
hey guys i couldn't repro that error.

what's your windows version? PS version? modules loaded and version? 
can you run a "get-Module" once you import this module?

**Comment by agallego-css** [comment]
ok. I got the repro in PS7.
Some how we fail to load the Microsoft.Identity.Client module in PS7 (works in PS5.1).

I can add the suggestion above.
but we still need to deal with the bug: https://github.com/agallego-css/ewsgui/issues/28

there's still a lot to learn here.

**Comment by agallego-css** [comment]
i have published the update in version 2.0.21.

please let me know if your issue is fixed.

**Comment by dkotars** [comment]
Version 2.0.21 now throws the error that it could not find Microsoft.IdentityModel.Abstractions/6.2.2.0 - I went to https://www.nuget.org/packages/Microsoft.IdentityModel.Abstractions/6.22.0.0 and extracted the files to bin as mentioned by arachnosoft to get it to work.

**Comment by agallego-css** [comment]
ok. let me update that and release the new version

**Comment by agallego-css** [comment]
guys. i have finally updated to version 2.0.27. please let me know if this time works fine for you. 
i have tested in 3 differente machines either in PS5.1 and PS7 and worked fine in all of them.
